### ISSUE TITLE
Mechanical Engineering is the only Engineering

### ISSUE THREAD

**Issue by ghost** [ivanskodje-godotengine/Vehicle-Controller-2D#2]
@ivanskodje  Ivan, you're not engineer. 

Stop falsely claiming to be an "Engineer". You know nothing about engineering. Engineering has nothing to do with sitting lazily behind a keyboard and writing code. Engineering is a real subject.

 Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. You software devs are claiming the most ridiculous of false claims these days. Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering. So stop the lies. You will never be engineers.

**Comment by ivanskodje** [comment]
This is a good #2 issue, but I will have to mark this as a Unplanned feature ❤️
